all:
  hosts:
    # localhost:
    #   ansible_host:         127.0.0.1
    #   ansible_connection:  local
    box:
      ansible_host:         192.168.0.29
      ansible_connection:   ssh
      ansible_user:         oiboone



