# execute via : sudo ansible-playbook engineering.yml
- hosts: active
  gather_facts: no
  become: true

#- import_playbook: standard_desktop.yml
#- import_playbook: multimedia.yml
#- import_playbook: engineering.yml
#- import_playbook: technical_writing.yml
